const verses = [
  "Chapter 2, Verse 47: You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions...",
  "Chapter 4, Verse 7: Whenever there is a decline in righteousness and an increase in unrighteousness, O Arjuna, at that time I manifest myself on earth...",
  "Chapter 2, Verse 19: He who thinks that the soul kills, and he who thinks of it as killed, are both ignorant. The soul kills not, nor is it killed...",
  "Chapter 2, Verse 20: The soul is neither born, nor does it die; nor having once been, does it ever cease to be. The soul is birthless, eternal, imperishable, and timeless...",
  "Chapter 2, Verse 22: As a person puts on new garments, giving up old ones, the soul similarly accepts new material bodies, giving up the old and useless ones...",
  "Chapter 2, Verse 23: The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind...",
  "Chapter 2, Verse 27: For one who has taken birth, death is certain; and for one who has died, birth is certain. Therefore, you should not lament over the inevitable...",
  "Chapter 2, Verse 30: O Arjuna, the soul that resides in the body is indestructible; therefore, you should not grieve for any living being...",
  "Chapter 2, Verse 40: In this endeavor, there is no loss or diminution, and a little advancement on this path can protect one from the greatest danger...",
  "Chapter 2, Verse 47: You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions...",
  "Chapter 2, Verse 48: Be steadfast in the performance of your duty, O Arjuna, abandoning attachment to success and failure. Such equanimity is called yoga...",
  "Chapter 3, Verse 9: Work done as a sacrifice for Vishnu has to be performed, otherwise work causes bondage in this material world. Therefore, O son of Kunti, perform your prescribed duties for His satisfaction, and in that way you will always remain free from bondage...",
  "Chapter 3, Verse 16: He who does not follow the cycle of sacrifice established by the Vedas is sinful and lives only for the delight of the senses; such a man lives in vain...",
  "Chapter 3, Verse 21: Whatever action is performed by a great man, common men follow. And whatever standards he sets by exemplary acts, all the world pursues...",
  "Chapter 3, Verse 27: The spirit soul bewildered by the influence of false ego thinks himself the doer of activities that are in actuality carried out by the three modes of material nature...",
  "Chapter 3, Verse 30: Therefore, O Arjuna, surrendering all your works unto Me, with full knowledge of Me, without desire for profit, with no claims to proprietorship, and free from lethargy, fight...",
  "Chapter 4, Verse 6: Although I am unborn and My transcendental body never deteriorates, and although I am the Lord of all living entities, I still appear in every millennium in My original transcendental form...",
  "Chapter 4, Verse 8: To deliver the pious and annihilate the miscreants, as well as to reestablish the principles of religion, I advent Myself millennium after millennium...",
  "Chapter 4, Verse 13: The four divisions of human society are created by Me according to the three modes of material nature and the work ascribed to them...",
  "Chapter 4, Verse 18: He who sees inaction in action and action in inaction is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities...",
  "Chapter 4, Verse 22: He who is satisfied with gain which comes of its own accord, who is free from duality and does not envy, who is steady both in success and failure, is never entangled, although performing actions...",
  "Chapter 5, Verse 10: One who performs his duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action, as the lotus leaf is untouched by water...",
  "Chapter 5, Verse 18: The humble sage, by virtue of true knowledge, sees with equal vision a learned and gentle Brahmana, a cow, an elephant, a dog, and a dog-eater...",
  "Chapter 6, Verse 5: One must elevate, not degrade, oneself by one's own mind. The mind is the friend of the conditioned soul, and his enemy as well...",
  "Chapter 6, Verse 6: For him who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his very mind will be the greatest enemy...",
  "Chapter 6, Verse 16: There is no possibility of one's becoming a yogi, O Arjuna, if one eats too much or eats too little, sleeps too much or does not sleep enough...",
  "Chapter 6, Verse 26: From wherever the mind wanders due to its flickering and unsteady nature, one must certainly withdraw it and bring it back under the control of the Self...",
  "Chapter 7, Verse 3: Out of many thousands among men, one may endeavor for perfection, and of those who have achieved perfection, hardly one knows Me in truth...",
  "Chapter 7, Verse 14: This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it...",
  "Chapter 7, Verse 19: After many births and deaths, he who is actually in knowledge surrenders unto Me, knowing Me to be the cause of all causes and all that is...",
  "Chapter 7, Verse 23: Men of small intelligence worship the demigods, and their fruits are limited and temporary. Those who worship the demigods go to the planets of the demigods, but My devotees ultimately reach My supreme abode...",
  "Chapter 8, Verse 5: And whoever, at the time of death, quits his body remembering Me alone at once attains My nature. Of this, there is no doubt...",
  "Chapter 8, Verse 15: After attaining Me, the great souls, who are yogis in devotion, never return to this temporary world, which is full of miseries, because they have attained the highest perfection...",
  "Chapter 9, Verse 4: By Me, in My unmanifested form, this entire universe is pervaded. All beings are in Me, but I am not in them...",
  "Chapter 9, Verse 22: To those who are constantly devoted and who worship Me with love, I give the understanding by which they can come to Me...",
  "Chapter 9, Verse 27: Whatever you do, whatever you eat, whatever you offer or give away, and whatever austerities you perform, do that, O son of Kunti, as an offering to Me...",
  "Chapter 9, Verse 30: Even if one commits the most abominable actions, if he is engaged in devotional service, he is to be considered saintly because he is properly situated in his determination...",
  "Chapter 9, Verse 31: He quickly becomes righteous and attains lasting peace. O son of Kunti, declare it boldly that My devotee never perishes...",
  "Chapter 10, Verse 8: I am the source of all spiritual and material worlds. Everything emanates from Me. The wise, who know this perfectly, engage in My devotional service and worship Me with all their hearts...",
  "Chapter 10, Verse 10: To those who are constantly devoted and who worship Me with love, I give the understanding by which they can come to Me...",
  "Chapter 10, Verse 11: To show them special mercy, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance...",
  "Chapter 10, Verse 20: I am the Self, O Gudakesha, seated in the hearts of all creatures. I am the beginning, the middle, and the end of all beings...",
  "Chapter 10, Verse 25: Of the great sages I am Bhrigu; of vibrations I am the transcendental Om. Of sacrifices I am the chanting of the holy names [japa], and of immovable things I am the Himalayas...",
  "Chapter 10, Verse 34: I am all-devouring death, and I am the generating principle of all that is yet to be. Among women, I am fame, fortune, fine speech, memory, intelligence, steadfastness, and patience...",
  "Chapter 11, Verse 32: I am time, the great destroyer of the worlds, and I have come here to engage all people. With the exception of you [the Pandavas], all the soldiers here on both sides will be slain...",
  "Chapter 12, Verse 13: One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor, who is free from false ego and equal both in happiness and distress, who is always satisfied and engaged in devotional service with determination, his mind and intelligence fixed on Me, such a devotee of Mine is very dear to Me...",
];

document.getElementById("get-verse").addEventListener("click", function () {
  const randomVerse = verses[Math.floor(Math.random() * verses.length)];
  document.getElementById("verse").innerText = randomVerse;
});
